package org.multi;

public class MultiProcessVSMultiTHread {

	public static void main(String[] args) {
		

	}
/*-->PROCESS-BASED MULTITPROCESSING
 * 
 * EACH PROCESS ALLOCATES A SEPARATE MEMORY AREA
 * 
 * A PROCESS IS HEAVYWEIGHT
 * 
 * COST OF COMMUNICATION BETWEEN THE PROCESS IS HIGH
 * 
 * SWITCHING FROM ONE PROCESS TO ANOTHER REQUIRES SOME TIME FOR SAVING AND LOADING 
 * REGISTER,MEMORY MAPS,UPDATING LIST
 * 
 * -->THREAD-BASED MULTITASKING
 * 
 * THREADS SHARE THE SAME ADDRESS SPACE
 * 
 * A THREAD IS LIGHTWEIGHT
 * 
 * COST OF COMMUNICATION BETWEEN THE THREAD IS LOW
 * 
 * THREAT IS SMALLEST UNIT OF PROCESSING**
 * 
 * EXAMPLE*******OS
 * 
 * MULTIPLE PROCESS INSIDE THE OS AND ONE PROCESS CAN HAVE MULTIBLE THREADS
 * 
 * NOTED**
 * 
 * AT A TIME ONE THREAD EXCUTED ONLY
 * 
 * 
 * JAVA PROVIDES THREAD CLASS TO ACHIEVE THREADPROGRAMMING
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 */
}
