package org.multi;

public class MultiThread {

	public static void main(String[] args) {
		
		

	}
/*THREAD 
 * 
 * ACTUALY MAIN IS THREAD
 * 
 * THE PROCESS IS DONE SEQUENCELY
 * 
 * MULTITHREADING IT IS A PROCESS OF EXECUTING MULTIPLE THREADS SIMULTANEOUSLY
 * 
 * A THREAD IS A LIGHTWEIGHT SUB-PROCESS ,THE SMALLEST UNIT OF PROCESSING
 * 
 * -->MULTITHREADING AND MULTIPROCESSING ACHIEVE MULTITASKING
 * 
 * -->WE USE MULTITHREADING MORE THAN MULTIPROCESSING BECAUSE THREADS USE A 
 * SHARED MEMORY AREA .THEY DON'T ALLOCATE SEPARATE MEMORY AREA SO SAVES MEMORY
 * THE CONTEXT BETWEEN THE THREADS TAKES LESS TIME THAN PROCESS
 * 
 * JAVA MULTITHREADING IS MOSTLY USED IN GAMES,ANIMATION,ETC
 * 
 *  ADVANTAGES OF THREAD
 *  
 *  YOU CAN PERFORM MANY OPERATIONS TOGETHER,SO IT SAVES THE TIME
 *  
 *  THREADS ARE INDEPENDENT, SO IT DOESN'T AFFECT OTHER THREADS IF EXCEPTION OCCURS 
 *  IN A SINGLE THREADS
 * 
 * THREAD **SCHEDUALER ASSAIGN THE THREAD TO CPU BETWEEN FRACTION OF MILLISECONDS
 * SCHEDUALAR SELECT DEFINE BELOW CONDITIONS
 * SELECT RAMDOM
 * SELECT TIME
 * SELECT PRIORITY
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 */
}
