package org.multi;

public class ServletJava {

	public static void main(String[] args) {
		
		

	}

/*SERVLET
 * 
 * IF WE DESIGN WEB PAGE WE PROVIDE SERVLET CLASS
 * 
 * IF LOT OF USERS ACCESS THE WEB PAGE IF AM ACCESS THE WEB PAGE SEND THE HTTPS
 * REQUEST AND OTHER WANT ACCESS SEND HTTPS REQUEST
 * 
 * THE WORK OF SERVLET IS HANDLE ALL THE REQUEST FROM THE USERS
 * 
 * LOT OF THREADS AVAILABLE IN SERVLET 
 * 
 * ASSAIGN THE THREAD TO THE USER
 * 
 * 
 * THIS PROCESS IS ACHIEVE BY MULTITHREADING CONCEPT
 * 
 * 
 * 
 * 
 * 
 * 
 */
}
