package org.cons;

interface Mlp
{
	//abstract  void met(); 
	
	void hr();
}

public class InterfaceTypes {

	public static void main(String[] args) {
		
		
		Mlp ni=()->System.out.println("JAMES");//LAMDA EXPRESSION
	
		//THE DEFINITION OF THE HR METHOD
		ni.hr();
		

	}
	
/*
 * INTERFACE TYPES
 * 
 * NORMAL INTERFACE
 * SINGLE ABSTRACT INTERFACE OR FUCTIONAL INTERFACE
 * MARKER INTERFACE
 * 
 * NORMAL INTERFACE
 * 
 * NORMAL INTERFACE HAVE MORE THAN ONE METHOD IN INTERFACE
 * 
 * 
 * SINGLE ABSTRACT METHOD OR FUNCTIONAL INTERFACE
 * 
 * INTERFACE HAVE ONLY ONE METHOD 
 * JAVA 1.17 IT CALLED SINGLE ABSTRACT METHOD IN JAVA 1.18 IT CALLED FUNCTIONAL INTERFACE
 * IT USE LAMDA EXPRESSION DERIVED FROM SCALA
 * 
 * MARKER INTERFACE
 * 
 * IN DON'T HAVE METHODS AND ANYTHING OR EMPTY INTERFACE
 * 
 * 
 * LAMDA EXPRESSION 
 * 
 * LAMDA EXPRESSION PASSIBLE THROUGH THE FUNCTIONAL INTERFACE ONLY HAVE ONE METHOD
 * BUT IT DOESN'T ACCOUNT THE DEFAULT METHOD
 * 
 * 
 * 
 */
}
